# This contains params to be used by the stages to train or predict
model:
  base_model: albert-base-v2
  use_fast: True
  padding: max_length
  max_length: 128
  truncation: True

Dataset:
  test_size: 0.1
  