# It contains all the configs required in the project

artifacts:
  DOWNLOAD_DATA_DIR: Data
  DOWNLOAD_DATA_NAME: Data.csv
  Dataset_dir: Dataset
  local_data_dirs_filename: atis_intents.csv
  ID2LABEL: id2label.json
  LABEL2ID: label2id.json
  LABEL_NUM: label_num.json
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BEST_MODEL_DIR: best_model
  #UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks

# source_download_dirs:
#   - path_to_data_1
#   - path_to_data_1
metric:
  metric_name: 'matthews_correlation'

local_data_dirs:
  - artifacts/data

source_download_dirs: 
  - ../outside_data/Text_Classification

